### ISSUE TITLE
Where to get "Key"

### ISSUE THREAD

**Issue by mitul-srashtasoft** [tiancheng91/google-cse#1]
First of thanks fro for this program, it's helpful.

I don't get "Key" there , can you please explain me, i want to convert it onto Nodejs so

![Screenshot from 2021-04-06 17-38-58](https://user-images.githubusercontent.com/73469192/113708738-39792680-96ff-11eb-972c-20d440fb2155.png)

Line Number : 126

**Comment by tiancheng91** [comment]
The old version of cse had a static key. this repo may not working now.  @mitul-srashtasoft

**Comment by mitul-srashtasoft** [comment]
can you help me ? for new version ?
